"use client";

import { Car, ChartLineUp, CheckCircle, Clock, CurrencyDollar, Gauge, GasPump, Receipt, SpinnerGap, SteeringWheel, TrendUp, WarningCircle } from "@phosphor-icons/react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../lib/supabase";

type Invoice={issue_date:string|null;amount_with_tax:number;paid_amount:number;status:string;source_system:string|null;updated_at:string;clients:{name:string}|null};
type Service={id:string;service_date:string;status:string;client_id:string|null;vehicle_id:string|null;km_start:number|null;km_end:number|null;notes:string|null;source_system:string|null;updated_at:string;clients:{name:string}|null};
type Expense={amount:number;category:string;status:string;expense_date:string;source_system:string|null;updated_at:string};
type Vehicle={id:string;name:string;plate:string;current_km:number;status:string};
type Finding={id:string;severity:string;description:string;status:string;created_at:string};

function money(value:number){return `S/ ${value.toLocaleString("es-PE",{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function Metric({title,value,note,tone,icon:Icon}:{title:string;value:string;note:string;tone:string;icon:any}){return <article className={`metric ${tone}`}><div className="metric-head"><span>{title}</span><i><Icon size={22}/></i></div><strong>{value}</strong><small><TrendUp size={14}/>{note}</small></article>}

export function LiveOwnerDashboard(){
  const [invoices,setInvoices]=useState<Invoice[]>([]),[services,setServices]=useState<Service[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[findings,setFindings]=useState<Finding[]>([]);
  const [weeks,setWeeks]=useState(12),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const alertsRef=useRef<HTMLElement|null>(null);
  const load=useCallback(async()=>{if(!supabase)return;setLoading(true);setError("");const [a,b,c,d,e]=await Promise.all([
    supabase.from("invoices").select("issue_date,amount_with_tax,paid_amount,status,source_system,updated_at,clients(name)").neq("status","Anulada"),
    supabase.from("services").select("id,service_date,status,client_id,vehicle_id,km_start,km_end,notes,source_system,updated_at,clients(name)").order("service_date"),
    supabase.from("expenses").select("amount,category,status,expense_date,source_system,updated_at").neq("status","Rechazado"),
    supabase.from("vehicles").select("id,name,plate,current_km,status").eq("active",true).order("name"),
    supabase.from("findings").select("id,severity,description,status,created_at").in("status",["Abierto","En revisión"]).order("created_at",{ascending:false})
  ]);const first=a.error||b.error||c.error||d.error||e.error;if(first)setError(first.message);else{setInvoices((a.data||[]) as unknown as Invoice[]);setServices((b.data||[]) as unknown as Service[]);setExpenses((c.data||[]) as Expense[]);setVehicles((d.data||[]) as Vehicle[]);setFindings((e.data||[]) as Finding[])}setLoading(false)},[]);
  useEffect(()=>{void load();if(!supabase)return;const client=supabase;const channel=client.channel("executive-live").on("postgres_changes",{event:"*",schema:"public",table:"services"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"invoices"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"expenses"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"findings"},()=>void load()).subscribe();return()=>{void client.removeChannel(channel)}},[load]);
  const metrics=useMemo(()=>{const billed=invoices.reduce((n,r)=>n+Number(r.amount_with_tax),0),collected=invoices.reduce((n,r)=>n+Number(r.paid_amount),0),spent=expenses.reduce((n,r)=>n+Number(r.amount),0);return{billed,collected,pending:Math.max(0,billed-collected),spent}},[invoices,expenses]);
  const series=useMemo(()=>{const now=new Date();return Array.from({length:weeks},(_,index)=>{const end=new Date(now);end.setDate(now.getDate()-(weeks-1-index)*7);const start=new Date(end);start.setDate(end.getDate()-6);const value=services.filter(s=>{const d=new Date(`${s.service_date}T12:00:00`);return d>=start&&d<=end}).length;return{label:`S${index+1}`,value}})},[services,weeks]);
  const clients=useMemo(()=>{const map=new Map<string,{services:number,billed:number}>();services.forEach(s=>{const name=s.clients?.name||"Sin cliente";map.set(name,{services:(map.get(name)?.services||0)+1,billed:map.get(name)?.billed||0})});invoices.forEach(i=>{const name=i.clients?.name||"Sin cliente";const current=map.get(name)||{services:0,billed:0};current.billed+=Number(i.amount_with_tax);map.set(name,current)});return [...map.entries()].map(([name,v])=>({name,...v})).sort((a,b)=>b.billed-a.billed).slice(0,6)},[services,invoices]);
  const incomplete=services.filter(s=>!s.client_id||!s.vehicle_id||s.km_start===null||s.km_end===null).length;
  const imported={services:services.filter(r=>r.source_system==="google_sheets").length,invoices:invoices.filter(r=>r.source_system==="google_sheets").length,expenses:expenses.filter(r=>r.source_system==="google_sheets").length};
  const anomalies=services.filter(r=>r.notes?.includes("Hallazgo de importación")).length;
  const lastSync=[...services,...invoices,...expenses].filter(r=>r.source_system==="google_sheets").map(r=>new Date(r.updated_at).getTime()).filter(Number.isFinite).sort((a,b)=>b-a)[0];
  function report(){const rows=[["REPORTE GERENCIAL DCS"],["Generado",new Date().toLocaleString("es-PE")],[],["Indicador","Valor"],["Facturado",metrics.billed],["Cobrado",metrics.collected],["Pendiente",metrics.pending],["Egresos",metrics.spent],["Servicios",services.length],["Hallazgos abiertos",findings.length],[],["Cliente","Servicios","Facturado"],...clients.map(c=>[c.name,c.services,c.billed])];const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`reporte-dcs-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
  if(loading)return <main className="content"><div className="empty-state"><SpinnerGap className="spin" size={30}/>Calculando indicadores…</div></main>;
  const max=Math.max(1,...series.map(s=>s.value)),maxClient=Math.max(1,...clients.map(c=>c.billed));
  return <main className="content"><section className="welcome"><div><span className="live-dot">EN VIVO</span><h2>Resumen gerencial DCS</h2><p>Indicadores calculados directamente desde la operación registrada.</p></div><button className="primary" onClick={report}><ChartLineUp size={19}/>Generar reporte</button></section>{error&&<div className="module-error"><WarningCircle size={20}/>{error}</div>}<section className="metrics-grid"><Metric title="Facturación" value={money(metrics.billed)} note={`${invoices.length} comprobantes`} tone="blue" icon={CurrencyDollar}/><Metric title="Cobrado" value={money(metrics.collected)} note={`${metrics.billed?((metrics.collected/metrics.billed)*100).toFixed(1):0}% de la facturación`} tone="green" icon={CheckCircle}/><Metric title="Pendiente" value={money(metrics.pending)} note={`${invoices.filter(i=>i.status==="Pendiente"||i.status==="Parcial").length} por cobrar`} tone="amber" icon={Clock}/><Metric title="Servicios" value={String(services.length)} note={`${services.filter(s=>s.status==="Completado").length} completados`} tone="purple" icon={SteeringWheel}/></section>
  <section className="dashboard-grid"><article className="panel chart-panel span-2"><div className="panel-title"><div><span>RENDIMIENTO OPERATIVO</span><h3>Servicios por semana</h3></div><select value={weeks} onChange={e=>setWeeks(Number(e.target.value))}><option value={4}>Últimas 4 semanas</option><option value={12}>Últimas 12 semanas</option><option value={24}>Últimas 24 semanas</option></select></div><div className="bar-chart">{series.map(s=><div className="bar-col" key={s.label}><span style={{height:`${Math.max(4,(s.value/max)*100)}%`}}><b>{s.value}</b></span><small>{s.label}</small></div>)}</div></article><article className="panel"><div className="panel-title"><div><span>FACTURACIÓN Y SERVICIOS</span><h3>Principales clientes</h3></div></div><div className="client-list">{clients.length?clients.map(c=><div key={c.name}><div><span>{c.name} · {c.services} serv.</span><strong>{money(c.billed)}</strong></div><i><b style={{width:`${(c.billed/maxClient)*100}%`,background:"#168091"}}/></i></div>):<div className="empty-state">Sin datos</div>}</div></article>
  <article className="panel vehicle-card"><div className="panel-title"><div><span>FLOTA</span><h3>Estado de unidades</h3></div><Gauge size={26}/></div>{vehicles.map(v=><div className="vehicle" key={v.id}><i className="vehicle-icon"><Car size={26}/></i><div><strong>{v.name} · {v.plate}</strong><span>{Number(v.current_km).toLocaleString("es-PE")} km</span></div><b className="status blue-status">{v.status}</b></div>)}<div className="fuel-row"><GasPump size={22}/><div><span>Combustible y egresos</span><strong>{money(metrics.spent)}</strong></div></div></article>
  <article ref={alertsRef} className="panel span-2"><div className="panel-title"><div><span>CONTROL</span><h3>Alertas que necesitan atención</h3></div><button onClick={()=>void load()}>Actualizar</button></div><div className="alerts"><div className="alert red"><WarningCircle size={22}/><div><strong>{incomplete} servicios incompletos</strong><span>Falta unidad, kilometraje o cliente.</span></div><b>Alta</b></div><div className="alert amber"><Receipt size={22}/><div><strong>{invoices.filter(i=>i.status==="Pendiente"||i.status==="Parcial").length} facturas pendientes</strong><span>Saldo por cobrar: {money(metrics.pending)}</span></div><b>Media</b></div><div className="alert teal"><WarningCircle size={22}/><div><strong>{findings.length} incidencias abiertas</strong><span>{findings[0]?.description||"Sin hallazgos pendientes."}</span></div><b>Control</b></div></div></article><article className="panel span-3 sync-health"><div className="panel-title"><div><span>INTEGRACIÓN GOOGLE SHEETS</span><h3>Estado de sincronización</h3></div><b className="status green-status">Operativa</b></div><div className="sync-stats"><div><strong>{imported.services}</strong><span>Servicios importados</span></div><div><strong>{imported.invoices}</strong><span>Facturas importadas</span></div><div><strong>{imported.expenses}</strong><span>Egresos importados</span></div><div className={anomalies?"sync-warning":""}><strong>{anomalies}</strong><span>Filas con hallazgos</span></div><div><strong>{lastSync?new Date(lastSync).toLocaleString("es-PE",{dateStyle:"short",timeStyle:"short"}):"Pendiente"}</strong><span>Última actualización</span></div></div></article></section></main>
}
